USE [master]
GO

CREATE DATABASE [ScreenRecognition]
GO
USE [ScreenRecognition]
GO

CREATE TABLE [Role](
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
)
GO

CREATE TABLE [Country](
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [Language](
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	TranslatorAlias NVARCHAR(50),
	OCRAlias NVARCHAR(50),
)
GO

CREATE TABLE OCR(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE Translator(
	ID INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE [User](
	ID INT IDENTITY PRIMARY KEY,
	RoleID INT FOREIGN KEY REFERENCES [Role](ID) NOT NULL,
	[Login] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	NickName NVARCHAR(100),
	[Email] NVARCHAR(MAX) NOT NULL,
	[FirstName] NVARCHAR(50),
	[LastName] NVARCHAR(50),
	CountryID INT FOREIGN KEY REFERENCES [Country](ID),
	Birthday DATE,
)
GO

CREATE TABLE Settings(
	UserID INT FOREIGN KEY REFERENCES [User](ID) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	SelectedOCRID INT FOREIGN KEY REFERENCES OCR(ID),
	SelectedTranslatorID INT FOREIGN KEY REFERENCES Translator(ID),
	TranslatorApiKey NVARCHAR(MAX),
	InputLanguageID INT FOREIGN KEY REFERENCES [Language](ID),
	OutputLanguageID INT FOREIGN KEY REFERENCES [Language](ID),
	ResultColor NVARCHAR(50),
	PRIMARY KEY(UserID, [Name]),
)
GO

CREATE TABLE History(
	ID INT NOT NULL,
	UserID INT FOREIGN KEY REFERENCES [User](ID) NOT NULL,
	Screenshot VARBINARY(MAX),
	SelectedOCRID INT FOREIGN KEY REFERENCES OCR(ID),
	RecognizedText NVARCHAR(MAX),
	RecognizedTextAccuracy FLOAT,
	SelectedTranslatorID INT FOREIGN KEY REFERENCES Translator(ID),
	InputLanguageID INT FOREIGN KEY REFERENCES [Language](ID),
	OutputLanguageID INT FOREIGN KEY REFERENCES [Language](ID),
	[Translate] NVARCHAR(MAX),
	PRIMARY KEY(UserID, ID),
)
GO